include:
  - _poststitle:  FGh.io
url:              https://fghio.github.io

# Links to include in top navigation
# For external links add external: true
links:
  - title: Curriculum
    url: /cv/
  - title: Blog
    url: /blog/
  - title: Articles
    url: /articles/
  - title: Projects
    url: /projects/
  - title: Readings
    url: /readings/
  - title: Publications
    url: /publications/
  - title: Tools
    url: /tools/

include: [".htaccess"]
